pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/mubashraiftikhar/jenkins.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t nginx-demo:${BUILD_NUMBER} .'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                    docker rm -f nginx-demo-run || true

                    docker run -d \
                        -p 8082:80 \
                        --name nginx-demo-run \
                        nginx-demo:${BUILD_NUMBER}
                '''
            }
        }

    }
}
